### ISSUE TITLE
Join Key System

### ISSUE THREAD

**Issue by reactivepixel** [ncarvalho/castr#28]
Convoluted for the users to use in it's current state. The help text that is needed to describe the steps a user would need to take seems significant. Possible better way to approach this as we discussed?

**Comment by reactivepixel** [comment]
Was this resolved? I still see the keys listed out in the listing of projects.

**Comment by ncarvalho** [comment]
I've added some helper text that appears when you click "Join Project." They keys are still there for sharing with other directors. Tonight, I am going to work on the filter needed to display projects that belong to certain directors since all the projects still appear.

**Comment by ncarvalho** [comment]
Getting together with Rachel on Wednesday to ask about my filter function that won't work.
